// Mock merchants and coupons for demo / seed
export const MOCK_CATEGORIES = [
  { id: "cat-1", nameKo: "맛집·카페", nameEn: "Food & Cafe", icon: "🍜" },
  { id: "cat-2", nameKo: "쇼핑", nameEn: "Shopping", icon: "🛍️" },
  { id: "cat-3", nameKo: "관광·체험", nameEn: "Tour & Activity", icon: "🗺️" },
  { id: "cat-4", nameKo: "뷰티·스파", nameEn: "Beauty & Spa", icon: "💆" },
  { id: "cat-5", nameKo: "숙박", nameEn: "Accommodation", icon: "🏨" },
];

export const MOCK_MERCHANTS = [
  {
    id: "m-1", nameKo: "인천 개항로 카페 1883", nameEn: "Cafe 1883 Incheon",
    categoryId: "cat-1", addressKo: "인천 중구 개항로 33", addressEn: "33 Gaehangro, Jung-gu, Incheon",
    lat: 37.4745, lng: 126.6172, thumbnailUrl: "https://picsum.photos/seed/cafe1883/400/300",
    description: "개항장 분위기의 클래식 카페. 한국 전통 디저트와 시그니처 음료.",
  },
  {
    id: "m-2", nameKo: "차이나타운 레스토랑 만리향", nameEn: "Manlihyang Chinese Restaurant",
    categoryId: "cat-1", addressKo: "인천 중구 차이나타운로 45", addressEn: "45 Chinatown-ro, Jung-gu, Incheon",
    lat: 37.4761, lng: 126.6198, thumbnailUrl: "https://picsum.photos/seed/manlihyang/400/300",
    description: "인천 차이나타운 대표 짜장면·짬뽕 전문점. 100년 전통.",
  },
  {
    id: "m-3", nameKo: "송도 신세계 면세점", nameEn: "Shinsegae Duty Free Songdo",
    categoryId: "cat-2", addressKo: "인천 연수구 센트럴로 70", addressEn: "70 Central-ro, Yeonsu-gu, Incheon",
    lat: 37.3926, lng: 126.6435, thumbnailUrl: "https://picsum.photos/seed/shinsegae/400/300",
    description: "K-뷰티·패션·명품 한 곳에. 외국인 관광객 추가 혜택 제공.",
  },
  {
    id: "m-4", nameKo: "영종도 씨사이드 게스트하우스", nameEn: "Yeongjong Seaside Guesthouse",
    categoryId: "cat-5", addressKo: "인천 중구 영종로 500", addressEn: "500 Yeongjong-ro, Jung-gu, Incheon",
    lat: 37.4917, lng: 126.4924, thumbnailUrl: "https://picsum.photos/seed/seaside/400/300",
    description: "인천공항 근처 바다 전망 게스트하우스. 셔틀버스 운행.",
  },
  {
    id: "m-5", nameKo: "을왕리 서핑 클럽", nameEn: "Eurwangni Surf Club",
    categoryId: "cat-3", addressKo: "인천 중구 을왕동 산65", addressEn: "San65 Eurwangdong, Jung-gu, Incheon",
    lat: 37.4577, lng: 126.3929, thumbnailUrl: "https://picsum.photos/seed/surfclub/400/300",
    description: "서해 최대 서핑 스팟. 장비 대여·강습 패키지.",
  },
  {
    id: "m-6", nameKo: "강화도 전통 한지 공방", nameEn: "Ganghwa Hanji Craft Studio",
    categoryId: "cat-3", addressKo: "인천 강화군 강화읍 북문길 15", addressEn: "15 Bukmun-gil, Ganghwa-eup, Ganghwa-gun",
    lat: 37.7488, lng: 126.4874, thumbnailUrl: "https://picsum.photos/seed/hanji/400/300",
    description: "전통 한지 뜨기 체험. 외국인 영어 설명 가능.",
  },
  {
    id: "m-7", nameKo: "송도 K-뷰티 스파", nameEn: "Songdo K-Beauty Spa",
    categoryId: "cat-4", addressKo: "인천 연수구 컨벤시아대로 165", addressEn: "165 Convensia-daero, Yeonsu-gu, Incheon",
    lat: 37.3889, lng: 126.6527, thumbnailUrl: "https://picsum.photos/seed/kbeauty/400/300",
    description: "K-뷰티 스킨케어·마사지 전문. 5개 국어 스태프 상주.",
  },
  {
    id: "m-8", nameKo: "인천공항 면세점 K-GIFT", nameEn: "KGIFT Airport Duty Free",
    categoryId: "cat-2", addressKo: "인천 중구 공항로 272 제1터미널", addressEn: "T1, 272 Gonghang-ro, Jung-gu, Incheon",
    lat: 37.4491, lng: 126.4509, thumbnailUrl: "https://picsum.photos/seed/kgift/400/300",
    description: "K-팝 굿즈·한국 특산품 전문 면세점. 출국 전 마지막 쇼핑.",
  },
];

export const MOCK_COUPONS = [
  {
    id: "c-1", merchantId: "m-1", categoryId: "cat-1",
    titleKo: "아메리카노 2+1", titleEn: "Buy 2 Get 1 Free Americano",
    titleJa: "アメリカーノ2+1", titleZh: "美式咖啡买二送一",
    descKo: "아메리카노 2잔 구매 시 1잔 무료 제공", descEn: "Free Americano when you buy 2",
    couponType: "GIFT", discountValue: 0, redeemMode: "SCREEN",
    barcodeValue: null, qrPayload: null,
    endsAt: new Date("2026-12-31"), thumbnailUrl: "https://picsum.photos/seed/cafe-coupon/400/300",
  },
  {
    id: "c-2", merchantId: "m-2", categoryId: "cat-1",
    titleKo: "짜장면 세트 20% 할인", titleEn: "Jjajangmyeon Set 20% OFF",
    titleJa: "チャジャン麺セット20%OFF", titleZh: "炸酱面套餐8折优惠",
    descKo: "짜장면+짬뽕+군만두 세트 20% 할인", descEn: "20% off Jjajang+Jjambbong+Dumplings set",
    couponType: "PERCENT", discountValue: 20, redeemMode: "QR_REVERSE",
    barcodeValue: null, qrPayload: "NFS-C2-JJAJANG-20PCT",
    endsAt: new Date("2026-12-31"), thumbnailUrl: "https://picsum.photos/seed/jjajang/400/300",
  },
  {
    id: "c-3", merchantId: "m-3", categoryId: "cat-2",
    titleKo: "외국인 추가 ₩10,000 할인", titleEn: "Extra ₩10,000 off for Foreigners",
    titleJa: "外国人追加1万ウォン割引", titleZh: "外国人额外优惠10000韩元",
    descKo: "₩50,000 이상 구매 시 ₩10,000 추가 할인", descEn: "₩10,000 extra off on purchases over ₩50,000",
    couponType: "FIXED", discountValue: 10000, redeemMode: "BARCODE",
    barcodeValue: "NFS-C3-DUTY-10000", qrPayload: null,
    endsAt: new Date("2026-12-31"), thumbnailUrl: "https://picsum.photos/seed/dutyfree/400/300",
  },
  {
    id: "c-4", merchantId: "m-4", categoryId: "cat-5",
    titleKo: "1박 15% 할인", titleEn: "15% Off One Night Stay",
    titleJa: "1泊15%OFF", titleZh: "住一晚85折",
    descKo: "평일 체크인 1박 15% 할인. 조식 포함", descEn: "15% off weekday stay, breakfast included",
    couponType: "PERCENT", discountValue: 15, redeemMode: "SCREEN",
    barcodeValue: null, qrPayload: null,
    endsAt: new Date("2026-12-31"), thumbnailUrl: "https://picsum.photos/seed/guesthouse/400/300",
  },
  {
    id: "c-5", merchantId: "m-5", categoryId: "cat-3",
    titleKo: "서핑 강습 ₩5,000 할인", titleEn: "₩5,000 Off Surf Lesson",
    titleJa: "サーフレッスン5,000ウォン割引", titleZh: "冲浪课程减5000韩元",
    descKo: "초급 2시간 강습 + 장비 대여 ₩5,000 할인", descEn: "₩5,000 off 2hr beginner lesson + equipment rental",
    couponType: "FIXED", discountValue: 5000, redeemMode: "QR_REVERSE",
    barcodeValue: null, qrPayload: "NFS-C5-SURF-5000",
    endsAt: new Date("2026-12-31"), thumbnailUrl: "https://picsum.photos/seed/surfing/400/300",
  },
  {
    id: "c-6", merchantId: "m-6", categoryId: "cat-3",
    titleKo: "한지 체험 1인 무료", titleEn: "1 Person Free Hanji Experience",
    titleJa: "韓紙体験1名無料", titleZh: "韩纸体验1人免费",
    descKo: "2인 이상 방문 시 1인 체험 무료", descEn: "1 person free when visiting in a group of 2+",
    couponType: "GIFT", discountValue: 0, redeemMode: "SCREEN",
    barcodeValue: null, qrPayload: null,
    endsAt: new Date("2026-12-31"), thumbnailUrl: "https://picsum.photos/seed/hanji2/400/300",
  },
  {
    id: "c-7", merchantId: "m-7", categoryId: "cat-4",
    titleKo: "K-뷰티 페이셜 30% 할인", titleEn: "K-Beauty Facial 30% OFF",
    titleJa: "K-Beautyフェイシャル30%OFF", titleZh: "K-Beauty护肤7折",
    descKo: "시그니처 K-뷰티 페이셜 60분 30% 할인", descEn: "30% off 60-min signature K-Beauty facial",
    couponType: "PERCENT", discountValue: 30, redeemMode: "BARCODE",
    barcodeValue: "NFS-C7-KBEAUTY-30PCT", qrPayload: null,
    endsAt: new Date("2026-12-31"), thumbnailUrl: "https://picsum.photos/seed/spa/400/300",
  },
  {
    id: "c-8", merchantId: "m-8", categoryId: "cat-2",
    titleKo: "K-팝 굿즈 세트 증정", titleEn: "Free K-Pop Goods Set",
    titleJa: "K-POPグッズセットプレゼント", titleZh: "赠K-Pop周边套装",
    descKo: "₩30,000 이상 구매 시 K-팝 굿즈 세트 증정", descEn: "Free K-Pop goods set on purchases over ₩30,000",
    couponType: "GIFT", discountValue: 0, redeemMode: "QR_REVERSE",
    barcodeValue: null, qrPayload: "NFS-C8-KPOP-GIFT",
    endsAt: new Date("2026-12-31"), thumbnailUrl: "https://picsum.photos/seed/kpop/400/300",
  },
];
